# Generated by Django 5.0.7 on 2024-07-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('start_time_interval', models.SmallIntegerField()),
                ('end_time_interval', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_interval', models.SmallIntegerField()),
                ('end_time_interval', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChartNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Non Binary')])),
                ('dob', models.DateField()),
                ('license_number', models.CharField(max_length=50)),
                ('practitioner_type', models.CharField(choices=[('physician', 'Physician'), ('nurse_practitioner', 'Nurse Practitioner'), ('physician_assistant', 'Physician Assistant'), ('chiropractor', 'Chiropractor'), ('physical_therapist', 'Physical Therapist'), ('acupuncturist', 'Acupuncturist'), ('massage_therapist', 'Massage Therapist')], max_length=50)),
                ('is_prescriber', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('time_interval_id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
