# Generated by Django 5.0.7 on 2024-07-24 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='chartnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='availability',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.day'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.day'),
        ),
        migrations.AddField(
            model_name='availability',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.practitioner'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.practitioner'),
        ),
    ]
