# Generated by Django 5.0.7 on 2024-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartnote',
            name='chart_note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_value',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
