# Generated by Django 5.0.7 on 2024-08-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_end_time_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='practitioner',
        ),
    ]
