# Generated by Django 5.0.7 on 2024-08-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_availability_day_and_more'),
        ('patients', '0003_alter_patient_primary_practitioner_and_more'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practitioners.practitioner'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Practitioner',
        ),
    ]
