# Generated by Django 5.0.7 on 2024-08-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_practitioner_delete_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartnote',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='appointments.appointment'),
        ),
    ]
