# Generated by Django 5.0.7 on 2024-08-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_insuranceinfo_patient'),
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='primary_practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practitioners.practitioner'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practitioners.practitioner'),
        ),
    ]
